### PR TITLE
Group Database

### PR DESCRIPTION
**Pull request by marwanelgharbawy**
## `Database.java`
- Add `parseGroupsData()` that works exactly like `parseUsersData()`, now both users and groups have the same JSON structure files.
- Add `Group` classes from the group branch that @minareda417 is working on. He'll be merging the class methods together when he's done.

## `Group.java`
- Add a constructor that takes the group ID after loading it from the database. No need to create one with JSON object as an argument since the `groups.json` file only contains the ID, so it's parsed in the database.
- Add a `setGroupData()` method similar to `setUserData()` that takes a JSON object. This method parses the JSON object and set the attributes accordingly. However, the part where it loads the admins and the members are commented out since they're not developed yet.

## Future modifications:
- @minareda417 will merge the group classes, updating them with the methods. There should be little merge conflicts
- After developing the Group, Member, and Admin classes, the "load admin and members data" in the `setGroupData()` should be implemented. They should take a User object as an argument.

### CODE REVIEW

**Review by omar-hekal — APPROVED** [review]

**Review by omar-hekal — CHANGES_REQUESTED** [review]
## change the `groups.json` format
make it a list of strings 
```json
[
"groupid1",
"groupid2",
"groupid3",
]
```

## modifiy func `parseGroupData` in `Database.java`
merge the 2 loops in `parseGroupData` into 1 loop

**Comment by marwanelgharbawy** [comment]
The `parseGroupsData()` will now read from a file with the format you mentioned.
Both loops have been merged now.

However, there isn't a method that writes back to the `groups.json` file. Currently working on it.

@omar-hekal

**Comment by marwanelgharbawy** [comment]
@omar-hekal check the `Database.java` and `Group.java`

I didn't include an example JSON file not tested it but it should work exactly like how the `parseUsersData()` works.

**Review by omar-hekal — APPROVED** [review]
well done

**Pull request merged**
