### PR TITLE
group

### PR DESCRIPTION
**Pull request by minareda417**

### CODE REVIEW

**Review by omar-hekal — COMMENTED** [review]
well done

**Review by marwanelgharbawy — APPROVED** [review]
I suggest not filling the class with unused setters and getters. They make the code a bit harder to read. We'll be removing them in the refactoring stage, but I suggest not doing this for future classes to be implemented.

**Comment by minareda417** [comment]
> I suggest not filling the class with unused setters and getters. They make the code a bit harder to read. We'll be removing them in the refactoring stage, but I suggest not doing this for future classes to be implemented.

The getters and setters in group class will be used later in the GUI.

**Comment by marwanelgharbawy** [comment]
okay, I pulled it and it had "no usages" so that's why.

**Pull request merged**
