### PR TITLE
Real Time File Updates

### PR DESCRIPTION
**Pull request by marwanelgharbawy**
# Backend Feature: Update Files in Real Time

The issue was the users' files weren't in sync with the database, so it was required to update these files with every modification happening in the program runtime.

# Class updates:

## `User.java`:

- Add a private `saveCredentials()` which calls the `writeDataToFiles()` in the database, which updates the `users.json` file.
- Link credentials setters (username, email, password) to the mentioned method to update it immediately, and also add their validations.
- Add a public `saveUser()` method which updates the user in the database. (This is exactly the same as calling `database.saveUser(user)`, so it can be deleted. It might be helpful if we need to update a user without having the database instance)
- Add the saveUser() method call after modifying the date of birth.
- Fix `loadRequests()` method to correctly update its lists.

## `Database.java`:
- Add `writeDataToFiles()` method call after saving a user, in case it was new.
- Add users to maps after saving them.

## FriendManager classes:
- Add missing `saveUser()` methods in its classes.

# Testing:
- We tested creating 3 different users, one of them has the 2 others as friends. Sending friend requests, accepting friend requests, and blocking friends update the files in real-time.

# Refactoring suggestions for the future:
- Change `parseUsersData()` method name to `loadUsersData()`.
- Change `writeDataToFiles()` method name  to `updateUsersCredentialsFile()` since it updates the `users.json` which has the users' credentials.

### CODE REVIEW

**Review by omar-hekal — APPROVED** [review]
impressive work

**Review by omar-hekal — CHANGES_REQUESTED** [review]
add real time update to profile

**Review by habibaswaify — APPROVED** [review]

**Review by minareda417 — APPROVED** [review]

**Review by minareda417 — APPROVED** [review]

**Review by minareda417 — APPROVED** [review]

**Comment by marwanelgharbawy** [comment]
## Latest changes:
- Bio was missing from the JSON object, so I added it. Now it can be extracted and set in the JSON object when loading and saving
- Separated setter methods with loading methods, to prevent writing in the database while loading.
- Changed `Profile.java`'s constructor to add it's own user, this helps when using setters, it can save by accessing the user reference and saving to the database.

@omar-hekal

**Review by omar-hekal — APPROVED** [review]
amazing work

**Pull request merged**
